input_filepath: "jeeadv2025-bench.json"
output_filepath: "./results/jeeadv2025_benchmark_results_grok_mini.json"
dbfilepath: "db/benchmark_results.db"
dotenv_filepath: "~/.env"
max_questions: null

solver_model_params:
  model: "openrouter/x-ai/grok-3-mini-beta"
  temperature: 0.3
  max_tokens: 8000
  num_retries: 1

grader_model_params:
  model: "gemini/gemini-2.0-flash-lite"
  temperature: 0.1
  num_retries: 2


